database:
  primary:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
  cache:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
pay:
  default_processor: fake_processor
redis:
  url: redis://localhost:6379/1
sso:
  google_oauth2:
    client_id: GOOGLE_CLIENT_ID
    client_secret: GOOGLE_CLIENT_SECRET
